- name: get installed boxes
  command: |
    vagrant box list
  register: installed_boxes
  changed_when: False

- name: install boxes
  command: |
    vagrant box add {{ item | quote }} {{ item | quote }}
  when: |
    vagrant.boxes and installed_boxes.stdout.find(item) == -1
  with_items: '{{ vagrant.boxes }}'

- name: get installed plugins
  command: |
    vagrant plugin list
  register: installed_plugins
  changed_when: False

- name: install plugins
  command: |
    vagrant plugin install {{ item | quote }}
  when: |
    vagrant.plugins and installed_plugins.stdout.find(item) == -1
  with_items: '{{ vagrant.plugins }}'
