#  Base
#-----------------------------------------------
[[plugins]] # dark powered vim/neovim plugin manager
repo = 'Shougo/dein.vim'

# WIP
#-----------------------------------------------
[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tpope/vim-endwise'

#[[plugins]]
#repo = 'todesking/ruby_hl_lvar.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # vim-jsx depends on this
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'cespare/vim-toml'
