- set_fact:
    anyenv: {}

- name: fetch anyenv repo
  git:
    repo: https://github.com/riywo/anyenv
    dest: '{{ anyenv.dir }}'
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: create plugins dir
  file:
    dest:  '{{ anyenv.plugins_dir }}'
    state: directory

- name: fetch anyenv update repo
  git:
    repo: https://github.com/znz/anyenv-update.git
    dest: '{{ anyenv.plugins_dir }}/anyenv-update'
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"
