anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

symlink:
  vim:                       .vim
  bash/.bash_profile:        .bash_profile
  bash/.bashrc:              .bashrc
  config/.ansible.cfg:       .ansible.cfg
  config/.aws/config:        .aws/config
  config/.curlrc:            .curlrc
  config/.peco:              .peco
  config/git/.gitconfig:     .gitconfig
  config/git/.gitignore:     .gitignore
  ruby/rbenv/default-gems:   .anyenv/envs/rbenv/default-gems
  vim/vimrc:                 .vimrc

python:
  versions:
    - '3.7.0'

ruby:
  versions:
    - '2.5.1'

  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'

  plugins:
    - ianheggie/rbenv-binstubs
    - sstephenson/rbenv-default-gems
    - sstephenson/rbenv-gem-rehash
