homebrew:
  applications:
    - clion
    - intellij-idea
    - iterm2
    - scroll-reverser
    - slack
    - zoomus
  packages:
    - bash-git-prompt # Informative, fancy bash prompt for Git users
    - coreutils       # GNU File, Shell, and Text utilities
    - mingw-w64       # Minimalist GNU for Windows and GCC cross-compilers
    - qemu            # Emulator for x86 and PowerPC

symlink:
  vim:                        .vim
  bash/.bash_profile:         .bash_profile
  bash/.bashrc:               .bashrc
  bash/.git-prompt-colors.sh: .git-prompt-colors.sh # Custom configuration file for magicmonty/bash-git-prompt
  config/.ansible.cfg:        .ansible.cfg
  config/.aws/config:         .aws/config
  config/.curlrc:             .curlrc
  config/.peco:               .peco
  config/git/.gitconfig:      .gitconfig
  config/git/.gitignore:      .gitignore
  ruby/rbenv/default-gems:    .anyenv/envs/rbenv/default-gems
  vim/vimrc:                  .vimrc

anyenv:
  dir:        '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path}}/.anyenv/plugins'
  envs_dir:   '{{ home_path }}/.anyenv/envs'

python:
  versions:
    - '3.7.0'

ruby:
  versions:
    - '2.5.1'

  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'

  plugins:
    - ianheggie/rbenv-binstubs
    - sstephenson/rbenv-default-gems
    - sstephenson/rbenv-gem-rehash
