homebrew:
  applications:
    - adobe-acrobat-reader
    - clion
    - eagle
    - evernote
    - google-backup-and-sync
    - google-chrome
    - intellij-idea
    - iterm2
    - karabiner-elements
    - kindle
    - scroll-reverser
    - slack
    - sublime-text
    - vagrant
    - virtualbox
    - zoomus
  packages:
    - bash-git-prompt # Informative, fancy bash prompt for Git users
    - cmake           # Cross-platform make
    - coreutils       # GNU File, Shell, and Text utilities
    - dosfstools      # Tools to create, check and label file systems of the FAT family
    - gcc             # GNU compiler collection
    - gptfdisk        # Text-mode partitioning tools
    - mingw-w64       # Minimalist GNU for Windows and GCC cross-compilers
    - qemu            # Emulator for x86 and PowerPC
    - wget            # Internet file retriever

symlink:
  vim:                        .vim
  bash/.bash_profile:         .bash_profile
  bash/.bashrc:               .bashrc
  bash/.git-prompt-colors.sh: .git-prompt-colors.sh # Custom configuration file for magicmonty/bash-git-prompt
  config/.ansible.cfg:        .ansible.cfg
  config/.aws/config:         .aws/config
  config/.curlrc:             .curlrc
  config/.peco:               .peco
  config/git/.gitconfig:      .gitconfig
  config/git/.gitignore:      .gitignore
  ruby/rbenv/default-gems:    .anyenv/envs/rbenv/default-gems
  vim/vimrc:                  .vimrc

system_symlink:
  # Use GNU gcc
  /usr/local/bin/gcc-9: /usr/local/bin/gcc
  /usr/local/bin/g++-9: /usr/local/bin/g++

anyenv:
  dir:        '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path}}/.anyenv/plugins'
  envs_dir:   '{{ home_path }}/.anyenv/envs'

python:
  versions:
    - '3.7.0'

ruby:
  versions:
    - '2.5.1'

  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'

  plugins:
    - ianheggie/rbenv-binstubs
    - sstephenson/rbenv-default-gems
    - sstephenson/rbenv-gem-rehash

vagrant:
  boxes:
    - ubuntu/xenial64 # Official Ubuntu 16.04 LTS (Xenial Xerus) builds
    - ubuntu/bionic64 # Official Ubuntu 18.04 LTS (Bionic Beaver) builds

  plugins:
    - sahara
