anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

symlink:
  bash/.bash_profile:        .bash_profile
  bash/.bashrc:              .bashrc
  config/.ansible.cfg:       .ansible.cfg
  config/.aws/config:        .aws/config
  config/.curlrc:            .curlrc
