- name:       Development environment managed by sykwer
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'

  environment:
    PATH: '/usr/local/bin:{{ anyenv.envs_dir }}/rbenv/shims:{{ anyenv.envs_dir }}/ndenv/shims:{{ anyenv.envs_dir }}/pyenv/shims:{{ anyenv.envs_dir }}/goenv/shims:{{ lookup("env", "PATH") }}'

  roles:
    #  basic
    #-----------------------------------------------
    - role: anyenv
      tags: ['basic', 'anyenv']
    - role: symlink
      tags: ['basic', 'symlink']

    #  lang
    #-----------------------------------------------
    - role: ruby
      tags: ['lang', 'ruby']

    #  app
    #-----------------------------------------------
    - role: vim
      tags: ['app', 'vim']
