- name:       Development environment managed by sykwer
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'

  roles:
    #  basic
    #-----------------------------------------------
    - role: symlink
      tags: ['basic', 'symlink']

    #  lang
    #-----------------------------------------------
    - role: anyenv
      tags: ['basic', 'anyenv']
    - role: python
      tags: ['lang', 'python']
    - role: ruby
      tags: ['lang', 'ruby']

    #  app
    #-----------------------------------------------
    - role: vim
      tags: ['app', 'vim']
