- name:       Development environment managed by sykwer
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'

  roles:
    #  basic
    #-----------------------------------------------
    - role: symlink
      tags: ['basic', 'basic.symlink']

    # install
    #-----------------------------------------------
    - role: homebrew
      tags: ['install', 'install.homebrew']

    #  lang
    #-----------------------------------------------
    - role: anyenv
      tags: ['lang', 'lang.anyenv']
    - role: python
      tags: ['lang', 'lang.python']
    - role: ruby
      tags: ['lang', 'lang.ruby']

    #  app
    #-----------------------------------------------
    - role: vim
      tags: ['app', 'app.vim']
